apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-devops-deployment
  labels:
    app: blog-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-devops
  template:
    metadata:
      labels:
        app: blog-devops
    spec:
      containers:
        - name: blog-devops
          image: blog-devops:latest   # ici on utilise ton image locale
          imagePullPolicy: Never      # tr√®s important pour que k8s ne cherche pas l'image sur Docker Hub
          ports:
            - containerPort: 3000
